name: Postman API Automated Test

on:
  push:
    branches: [ "main" ]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      # 1. 내 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 서버에 Postman CLI 설치하기
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # 3. 내 API 키로 로그인하기 (GitHub Secrets 사용)
      - name: Login to Postman
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # 4. Postman 컬렉션 실행하기
      - name: Run API Tests
        run: postman collection run 37510793-5982543a-f5fd-4ba5-9e19-6340246f97d2
